apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-user-dp
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  replicas: {{ .Values.deploy.app.replicaCount }}
  selector:
    matchLabels:
      env: {{ .Release.Name }}-app-user-label
  template:
    metadata:
      labels:
        env: {{ .Release.Name }}-app-user-label
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.app.repository }}/{{ .Values.image.app.tag }}:{{ .Values.image.app.version }}
          ports:
          - containerPort: {{ .Values.service.app.port }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: db-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: db-port
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: db-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-root-password
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.app.port }}
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.app.port }}
            successThreshold: 1
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-app-user-config
            items:
              - key: application.properties
                path: application.properties
