apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-user-svc
spec:
  selector:
    env: {{ .Release.Name }}-app-user-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.app.port }}
  type: {{ .Values.service.app.type }}
