apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-user-ing
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.app.host }}
      http:
        paths:
          - path: {{ .Values.ingress.app.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-app-user-svc
                port:
                  number: 80
