apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-runner
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - image: 'liquibase/liquibase:4.25'
          name: liquibase
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              lpm add mysql --global \
              && \
              liquibase update \
              --classpath=/workspace/liquibase \
              --changeLogFile=master.xml \
              --url=jdbc:mysql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME) \
              --username=$(DATABASE_USER) \
              --password=$(DATABASE_PASSWORD)
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-mysql
                  key: db-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-mysql
                  key: db-port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: db-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: db-password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-mysql
                  key: db-name
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      initContainers:
        - command: [ "/bin/sh", "-c" ]
          args: ["git clone --single-branch --branch $(BRANCH) $(REPO) /workspace"]
          env:
            - name: BRANCH
              value: master
            - name: REPO
              value: 'https://github.com/alexey-belov1/otus-microservices'
          image: alpine/git
          name: git
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      restartPolicy: Never
      volumes:
        - emptyDir: {}
          name: workspace
