apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-liquibase-runner-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.liquibase.repository }}/{{ .Values.image.liquibase.tag }}:{{ .Values.image.liquibase.version }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              lpm add mysql --global \
              && \
              liquibase update \
              --classpath=/workspace/liquibase \
              --changeLogFile=master.xml \
              --url=jdbc:mysql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME) \
              --username=$(DATABASE_USER) \
              --password=$(DATABASE_PASSWORD)
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: db-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: db-port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: db-password
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-config
                  key: db-name
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      initContainers:
        - command: [ "/bin/sh", "-c" ]
          args: ["git clone --single-branch --branch $(BRANCH) $(REPO) /workspace"]
          env:
            - name: BRANCH
              value: {{ .Values.initContainer.git.branch }}
            - name: REPO
              value: {{ .Values.initContainer.git.repo }}
          image: {{ .Values.image.git.repository }}/{{ .Values.image.git.tag }}
          name: git
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      restartPolicy: Never
      volumes:
        - emptyDir: {}
          name: workspace
