apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
spec:
  storageClassName: {{ .Release.Name }}-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.pv.mysql.path }}
    type: {{ .Values.pv.mysql.type }}
