apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-svc
spec:
  selector:
    env: {{ .Release.Name }}-mysql-label
  ports:
    - port: {{ .Values.service.mysql.port }}
  type: {{ .Values.service.mysql.type }}
